# Generated by Django 4.2.30 on 2026-05-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Маркеры', 'Маркеры'), ('Маски', 'Маски'), ('Баллоны', 'Баллоны'), ('Защита', 'Защита'), ('Аксессуары', 'Аксессуары')], max_length=20)),
                ('emoji', models.CharField(default='🎯', max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('old_price', models.PositiveIntegerField(blank=True, null=True)),
                ('badge', models.CharField(blank=True, choices=[('new', 'Новинка'), ('sale', 'Скидка'), ('hit', 'Хит')], max_length=10, null=True)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('in_stock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
